# Site settings
title: みなとRuby会議02
header-img: img/239259029_fe32cae13a_b.jpg
#email: your-email@yourdomain.com
description: "みなとRuby会議02 is held by yokohama.rb."
baseurl: ""
url: "http://yokohamarb.github.io"
twitter_username: yokohamarb
github_username:  yokohamarb

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
